### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by mehcode** [bh/atom-python-isort#15]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (/usr/share/atom/resources/app.asar/exports/atom.js:48:11)
Object.<anonymous> (/home/ryan/.atom/packages/python-isort/lib/python-isort.coffee:2:20)
Object.<anonymous> (/home/ryan/.atom/packages/python-isort/lib/python-isort.coffee:105:4)
Module._compile (module.js:452:26)
Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
Module.load (module.js:347:32)
```

**Comment by MateuszG** [comment]
+1
